### ISSUE TITLE
#Task 2.3.1: Sequence Diagram 1

### ISSUE THREAD

**Issue by hxijxe** [hxijxe/ict-inf2001-p3-6#27] opened 2023-09-16 03:13 UTC

**Comment by Kohgi88** [comment] 2023-10-27 11:00
Task title ID: 2.3.1 

What is the task about? Please describe in detail.
Utilize sequence diagrams to illustrate the interactions between system objects for each use case, enabling the delivery of the desired functionality.

What are the goals of the task? Please describe in detail.
Visually illustrate the interactions between system components, assist understanding and communication with others so that the system behaves as intended. Furthermore, relying on these diagrams for documentation aids in planning component integration and troubleshooting. 

Success or completion criteria. Please describe in detail.
NA

Allocated time
4 days

Start date and end date of the issue/task
20/10/23 - 24/10/23

Who is the owner? The owner is the person in-charge of the task and the task should be created and maintained by the owner.
@Kohgi88

The status of the task. This is usually "To-Do" initially.
Completed

What is the Priority of the task?
High 

Describe the work done in detail.
![Image](https://github.com/hxijxe/ict-inf2001-p3-6/assets/113673421/f04546fc-d1a0-4436-a9fc-e0acd6d5d8c8)

Has this work been committed to the repo?
Yes.

How does the work affect the completion deadline.
NA

Are there any changes to the success or completion criteria of the task? If yes, please describe the details.
NA

Start date and end date of the work done for this comment.
Start date: 20/10/23
End date: 24/10/23

**Closed as completed** 2023-10-30 13:15 UTC
Labels: documentation
