### ISSUE TITLE
#Task 1.3.2: Detailed Use Case Description (UC-1 to UC-4)

### ISSUE THREAD

**Issue by viviannzh** [hxijxe/ict-inf2001-p3-6#8] opened 2023-09-12 06:23 UTC

**Comment by Kohgi88** [comment] 2023-09-21 13:12
Task title ID:1.3.2 

What is the task about? Please describe in detail.
Generate a detailed Use Case Description via a structured document that outlines the details of a specific use case in software development or system design.

What are the goals of the task? Please describe in detail.
Provide a clear and comprehensive description of how a particular functionality or feature of a system will behave from the perspective of an actor (which can be a user, system, or external entity).

Success or completion criteria. Please describe in detail.
NA

Allocated time
6 days

Start date and end date of the issue/task
13/09/23 - 19/09/23

Who is the owner? The owner is the person in-charge of the task and the task should be created and maintained by the owner.
@Kohgi88

The status of the task. This is usually "To-Do" initially.
Completed

What is the Priority of the task?
High

Describe the work done in detail.
Use Case ID:
UC-1

Use Case Name:
Manage accounts

Description:
To manage accounts in the system, including creating, updating and deleting of accounts.

Primary Actor:
IT admin
Preconditions:
The IT admin is logged into the system.
The IT admin has the necessary permissions to manage accounts.

Postconditions:
Manager has successfully created, updated, or deleted accounts as needed.

Main Success Scenarios:
User Logs into System
System determines the user role and displays the corresponding landing page.
The IT admin selects the "Manage Accounts" option from the admin dashboard.
The system presents a list of existing accounts.
The IT admin selects the “Create Account” option from the system
The system presents a form for adding new staff or managers.
The IT admin fills in the required information for the new staff or manager, including their name, staff identification number, and role.
The IT admin submits the form.
The system validates the information and checks for any conflicts or errors.
System creates the new staff or manager to the system's database.
The system confirms the successful addition of the new staff or manager and provides a notification to the IT admin.

Alternative Scenarios:
5a. Update Account
5a1. The IT admin selects the "Update Accounts" option on the selected account.
5a2. The system presents a form with existing information of selected account
5a3. The IT admin fills in the new information for the selected staff or manager
5a4. The IT admin submits the form.
5a5. The system validates the information and checks for any conflicts or errors.
5a6. System updates the staff or manager to the system's database.
5a7. The system confirms the successful update of the staff or manager and provides a notification to the IT admin.

5b. Delete Account
5b1. The IT admin selects the "Delete Accounts" option on the selected account.
5b2. The system presents a form to confirm deletion.
5b3. The IT admin confirms the deletion
5b4. The system deletes the selected staff or manager from the system's database.
5a5. The system confirms the successful deletion of the staff or manager and provides a notification to the IT admin.

10a. Conflicts or errors in the information provided by the IT admin (e.g., duplicate staff identification number), 
10a1. The system displays an error message and prompts the IT admin to correct the information.
10a2. Repeat from Step 6

2a. User lacks the necessary permissions to manage account 
2a1. The system displays an error message and denies access to the "Manage Accounts" functionality.
2a2. Repeat from Step 1

10a. System experiences technical issues during the account management process
10a1. System notifies the IT admin of the problem and suggests retrying later or contacting technical support.

----------------------------------------------------------------------------------------------------------------

Use Case ID:
UC-2

Use Case Name:
Receive Acknowledgement

Description:
This use case outlines the interaction between staff members and managers/administrators regarding the acceptance or rejection of assigned shifts. It also includes the handling of reasons for shift rejection.

Primary Actor:
Staff

Preconditions:
Staff must be logged into the system 
Staff must have an assigned shift or work assignment that they wish to reject
Staff have requested to reject the assigned shift with reason
Manager / IT admin is logged into the system.

Postconditions:
The assigned shift is canceled only if the reason for rejection is accepted by the manager
If the rejection is accepted, the shift or work assignment becomes available for reassignment
If the rejection is not accepted, the security staff remains responsible for the assigned shift
Staff will receive an acknowledgement of the final decision

Main Success Scenarios:
Staff logs into the system.
The system displays a list of the staff's assigned shifts or work assignments.
Staff selects a specific shift or work assignment they want to reject.
The system prompts the security staff to provide a valid reason for the rejection.
Staff enters a valid reason for the rejection and submit.
The rejection request is submitted to the system.
The system sends a notification to the manager about the rejection request.
The manager reviews the rejection request and the provided reason.
If the system administrator accepts the rejection, the shift or work assignment is canceled, and the security staff is notified.
If the manager does not accept the rejection, the shift or work assignment remains unchanged, and the staff is notified of the decision.

Alternative Scenarios:
2a. System encounters an error and is unable to display information
2a1. Staff should receive an error message indicating the issue
2a2. The error message should include a description of the problem 
2a3. An option will be provided to retry the operation or contact technical support for assistance.
2a4. If the situation persists, staff may need to try again later when the system is functioning correctly.

8a. If the manager is unavailable to review the rejection request,
8a1. The system should have a mechanism for notifying another authorized user to handle the review.

9a. If the manager accepts the rejection, the system should ensure that the canceled shift is appropriately reassigned to another available staff
10a. If the staff rejects the rejection request, the system should provide a clear explanation for the decision to him/her.
10a1.The system should maintain a log of all rejection requests, including the reasons provided and the manager’s decisions, for audit and tracking purposes.

----------------------------------------------------------------------------------------------------------------

Use Case ID:
UC-3

Use Case Name:
Standby Shift

Description:
This use case outlines the process of activating a standby shift when a security staff is unable to fulfill their scheduled shift due to an emergency or non-appearance. The standby officer is assigned to replace the unavailable officer, and the shift is adjusted accordingly. Remuneration for standby officers is also managed through this process.

Primary Actor:
Staff

Preconditions:
Every shift will have designated standby staff available 
The staff originally assigned to a shift is unable to make it due to an emergency or no-show.
The system administrator is logged into the system

Postconditions:
The standby staff is assigned to the shift in place of the unavailable security staff.
The shift details are adjusted to reflect the change in staff
Remuneration for the standby officer is processed 

Main Success Scenarios:
The system identifies the unavailability of the scheduled security staff.
The system notifies the IT Admin and standby staff of the unavailability.
The standby staff is selected to replace the unavailable staff member
The standby staff confirms the assignment
The IT admin reviews and confirms the assignment
Remuneration Processing confirmation by the system
The standby staff reviews and confirms the remuneration processing

Alternative Scenarios:
2a. Standby staff becomes unavailable
2a1. The system identifies the unavailability of the selected replacement officer
2a2. The system notifies the IT Admin or manager about the standby staff’s unavailability
2a3.An alternative standby staff if available, is selected.
2a4. The shift details are updated

----------------------------------------------------------------------------------------------------------------

Use Case ID:
UC-4

Use Case Name:
Filter Shifts

Description:
This use case outlines the process by which security staff are categorized based on their competency levels through the submission of certificates. Managers can then use these competency categories to filter and assign suitable shifts based on the required skills and qualifications, while ensuring that staff members who have already booked a particular shift will not be displayed in the available pile for that specific shift. This prevents shifts from being double-booked and eliminates the possibility of conflicting assignments.

Primary Actor:
IT Admin, Manager

Preconditions:
The security staff have submitted their qualification certificates
The system has categorized them based on their competencies
Shifts or job assignments have been created in the system
The system has up-to-date information on the availability of each security staff member, indicating their free slots or times when they are not already scheduled for other shifts.

Postconditions:
The manager successfully filters and assigns shifts based on the competency levels and availability of security staff.

Main Success Scenarios:
The IT Admin ensures that security staff are required to submit their qualification certificates for verification
The system categorizes security staff into competency levels based on their submitted certificates
The system has up-to-date information on the availability of each security staff member, indicating their free slots or times when they are not already scheduled for other shifts
Shifts or job assignments have been created in the system.
The manager logs into the system and accesses the list of available shifts or job assignments
The manager selects the “Filter by competency” options to view and filter shifts based on the competency categories
The system displays a list of shifts that match the selected competency criteria
The system further refines the available shifts by considering the real-time availability data of the staff
 The manager is presented with a list of shifts that match the selected criteria and staff availability.
The manager selects an appropriate shift from the filtered list, ensuring that the assigned security staff are both competent and available.
The system records the shift assignment, updating the schedule accordingly.

Alternative Scenarios:
1a. Technical issues with certificate verification
1a1. Verification fails due to technical errors
1a2. The system logs the issue for IT support and security staff will not be categorized until the issue is resolved

5a. Invalid login credentials
5a1. The system displays an error message and prevents access
5a2. Manager is unable to proceed with filtering and assignments until valid credentials are provided

8a.Insufficient staff availability 
8a1. The system will notify the manager that there are no staff available with both the required competency and availability for the selected shift
8a2. The manager may need to reconsider the timing or competency criteria, or request additional staff members to fulfill the required criteria

Has this work been committed to the repo?
Yes.

How does the work affect the completion deadline.
NA

Are there any changes to the success or completion criteria of the task? If yes, please describe the details.
NA

Start date and end date of the work done for this comment.
Start date: 13/09/23
End date: 19/09/23

**Closed as completed** 2023-09-23 07:42 UTC
Labels: documentation
